#ifndef QMIME_GLOBAL_H
#define QMIME_GLOBAL_H
#include <QtCore/qglobal.h>
#if defined(QGAMECONTROLLER_LIBRARY)
# define QGAMECONTROLLER_EXPORT Q_DECL_EXPORT
#else
# define QGAMECONTROLLER_EXPORT Q_DECL_IMPORT
#endif
#endif // QMIME_GLOBAL_H